version: 2
jobs:
  build:
    environment:
      TZ: "Asia/Tokyo"
    docker:
      - image: circleci/php:8.0-node-browsers
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_USER: root
          MYSQL_HOST: 127.0.0.1

    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install intl
            sudo docker-php-ext-install pdo_mysql
      - run:
          name: Fix MySQL socket config
          command: |
            sudo sh -c "echo 'pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' > /usr/local/etc/php/conf.d/pdo.ini"
      - run:
          name: install php extension gd
          command: |
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd

      - run:
          name: composer install
          command: |
            sudo composer install -n --prefer-dist

      - run:
          name: PHP Stan(Account)
          command: ./vendor/bin/phpstan analyze --level 1 account


      - run:
          name: PHP Stan(Lesson)
          command: ./vendor/bin/phpstan analyze --level 1 lesson

      - run:
          name: PHP Stan(overcome)
          command: ./vendor/bin/phpstan analyze --level 1 Index